// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test5Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test5() {
    driver.get("https://www.google.com/");
    driver.manage().window().setSize(new Dimension(1280, 800));
    driver.findElement(By.cssSelector(".ng-star-inserted > .passiveLink img")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".menu-item-tag > .passiveLink"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    js.executeScript("window.scrollTo(0,123)");
    js.executeScript("window.scrollTo(0,1825)");
    driver.findElement(By.cssSelector(".menu-item-tag > .passiveLink")).click();
    driver.findElement(By.linkText("Register Now")).click();
    driver.findElement(By.cssSelector(".section-container")).click();
    js.executeScript("window.scrollTo(0,116)");
    js.executeScript("window.scrollTo(0,268)");
    {
      WebElement element = driver.findElement(By.cssSelector(".menu-items:nth-child(1) .menu-item"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
  }
}
