// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test14Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test14() {
    driver.get("https://www.wikipedia.org/");
    driver.manage().window().setSize(new Dimension(1280, 800));
    {
      WebElement element = driver.findElement(By.linkText("Paytm for Consumer"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Paytm for Consumer")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Paytm For Business")).click();
    driver.findElement(By.linkText("Consumer Payments")).click();
    js.executeScript("window.scrollTo(0,129)");
    driver.findElement(By.id("Online Payments")).click();
    driver.findElement(By.id("text-box")).sendKeys("hyder");
    driver.findElement(By.cssSelector(".\\_2xgL:nth-child(2) b")).click();
    driver.findElement(By.cssSelector(".col-xs-2:nth-child(4) #text-box")).click();
    driver.findElement(By.cssSelector(".\\_2xgL:nth-child(4) .\\_1TxU")).click();
    driver.findElement(By.cssSelector(".uOj_")).click();
    driver.findElement(By.cssSelector(".button")).click();
  }
}
