// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test10Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test10() {
    driver.get("https://www.wikipedia.org/");
    driver.manage().window().setSize(new Dimension(1280, 800));
    driver.findElement(By.linkText("Schedule")).click();
    driver.findElement(By.linkText("Home")).click();
    driver.findElement(By.linkText("View Special Eligibilities")).click();
    assertThat(driver.switchTo().alert().getText(), is("You are being redirected to an external website. Please note that CENTRALIZED COUNSELLING FOR M.TECH./M.ARCH./M.PLAN. ADMISSIONS cannot be held responsible for external websites content & privacy policies."));
    vars.put("handle=vars.get("win3259").toString()", driver.getWindowHandle());
  }
}
