# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLeetCode():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_leetCode(self):
    self.driver.get("https://leetcode.com/problemset/all/")
    self.driver.set_window_size(1106, 632)
    self.driver.execute_script("window.scrollTo(0,148.6666717529297)")
    self.driver.find_element(By.LINK_TEXT, "1519. Number of Nodes in the Sub-Tree With the Same Label").click()
    element = self.driver.find_element(By.LINK_TEXT, "1519. Number of Nodes in the Sub-Tree With the Same Label")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".px-4:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".px-4:nth-child(3)").click()
  
