# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAllnovel():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_allnovel(self):
    self.driver.get("https://allnovel.net/")
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(2) > .list-category").click()
    self.driver.execute_script("window.scrollTo(0,105.5999984741211)")
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-2:nth-child(9) .title-home-novel").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(9) > .list-category")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "a > .btn-success").click()
    self.driver.set_window_size(1536, 824)
  
