# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMygov():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_mygov(self):
    self.driver.get("https://www.mygov.in/")
    self.driver.set_window_size(1536, 824)
    self.driver.find_element(By.CSS_SELECTOR, ".poll-icon > i").click()
    self.driver.find_element(By.CSS_SELECTOR, ".creative-list .views-row:nth-child(2) > .views-field:nth-child(1) a").click()
    self.driver.find_element(By.ID, "edit_search").click()
    self.driver.find_element(By.ID, "edit_search").send_keys("republic day")
    self.driver.find_element(By.ID, "edit_search_btn").click()
    self.driver.find_element(By.ID, "edit_search_btn").click()
  
