# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestWikipedia():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_wikipedia(self):
    self.driver.get("https://www.wikipedia.org/")
    self.driver.set_window_size(1536, 824)
    self.driver.find_element(By.ID, "searchInput").send_keys("india")
    self.driver.find_element(By.CSS_SELECTOR, ".svg-search-icon").click()
    self.driver.find_element(By.LINK_TEXT, "India (disambiguation)").click()
  
