# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTutorialsPoint():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tutorialsPoint(self):
    self.driver.get("https://www.tutorialspoint.com/java/index.htm")
    self.driver.set_window_size(1192, 649)
    self.driver.execute_script("window.scrollTo(0,528.6666870117188)")
    self.driver.find_element(By.CSS_SELECTOR, ".toc:nth-child(3) > li:nth-child(3)").click()
    self.driver.execute_script("window.scrollTo(0,898)")
    self.driver.find_element(By.LINK_TEXT, "Java - Files and I/O").click()
    self.driver.execute_script("window.scrollTo(0,1431.3333740234375)")
  
